---
- name: Config Vim
  hosts: localhost
  become: yes
  vars:
    vimrc: "/etc/vim/vimrc.local"
  tasks:
    - name: Install Vim
      package:
        name:
          - vim
        state: present
    - name: Set up vimrc.local in place
      copy:
        src: vimrc
        dest: "{{ vimrc }}"
        backup: yes
        mode: 0644
